2024-11-24 09:49:50,443 - {'optimizer': {'name': 'adam', 'lr': 0.001, 'weight_decay': 0}, 'train': {'epoch': 500, 'batch_size': 4096, 'save_model': False, 'loss': 'pairwise', 'log_loss': False, 'test_step': 3, 'patience': 5, 'reproducible': True, 'seed': 2023, 'early_stop': True}, 'test': {'metrics': ['recall', 'ndcg'], 'k': [10, 20, 40], 'batch_size': 1024}, 'data': {'type': 'social', 'name': 'yelp', 'user_num': 43043, 'item_num': 66576}, 'model': {'name': 'idea_lightgcn', 'layer_num': 2, 'reg_weight': 1e-08, 'embedding_size': 64, 'self_gating_unit': True, 'pagerank': True, 'combine_gcn': False, 'alpha': 0.8, 'cl_weight': 1e-05, 'sigma': 20}, 'tune': {'enable': True, 'hyperparameters': ['layer_num', 'reg_weight', 'cl_weight', 'alpha'], 'layer_num': [2, 3], 'reg_weight': [1e-06, 1e-07, 1e-08], 'cl_weight': [1e-05, 1e-06, 1e-07], 'alpha': [0.7, 0.8, 0.9]}, 'device': 'cuda', 'log': True}
2024-11-24 09:49:50,444 - hyperparameter: {'layer_num': 2, 'reg_weight': 1e-06, 'cl_weight': 1e-05, 'alpha': 0.7}
2024-11-24 09:49:54,556 - expand is unsupported for Sparse tensors
Traceback (most recent call last):
  File "/home/doyunchoi/ds535/trainer/utils.py", line 15, in wrapper
    return func(*args, **kwargs)
  File "/home/doyunchoi/ds535/trainer/trainer.py", line 128, in train
    self.train_epoch(model, epoch_idx)
  File "/home/doyunchoi/ds535/trainer/trainer.py", line 83, in train_epoch
    loss.backward()
  File "/home/doyunchoi/.conda/envs/ds535/lib/python3.10/site-packages/torch/_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "/home/doyunchoi/.conda/envs/ds535/lib/python3.10/site-packages/torch/autograd/__init__.py", line 289, in backward
    _engine_run_backward(
  File "/home/doyunchoi/.conda/envs/ds535/lib/python3.10/site-packages/torch/autograd/graph.py", line 769, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: expand is unsupported for Sparse tensors
